version: '3'
# Descrição dos serviços 
services:
  # nome do servico
  dbpostgres:
    # imagem a ser utilizada
    image: postgres
    # volumes que serão compartilhados local:container
    volumes: 
      - /mnt/c/Users/Raphael Silvestre/temp/database:/var/lib/postgresql/data
    #porta compartilhada
    ports: 
      - 5432 : 5432
    environment: 
      - 'POSTGRES_PASSWORD' : 1234